services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql
volumes:
 db_data: